# StudyAI - Ansible Inventory
# Replace the IP with your EC2 instance public IP from Terraform output

[webservers]
studyai-prod ansible_host=54.162.235.197

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/studyai-prod-key.pem
ansible_python_interpreter=/usr/bin/python3
